const items = [
  {
    Weapons: 'Falchion',
    Category: '1-H Edged',
    Notes: '',
    Fumble: '1-5',
    Weight: '5.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Bastard Sword',
    Category: '1-Hand/2-Hand',
    Notes: '',
    Fumble: '1-4/1-5',
    Weight: '6.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Battle-Axe',
    Category: '2-Handed',
    Notes: '',
    Fumble: '1-5',
    Weight: '7.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Bola',
    Category: 'Missile',
    Notes: '',
    Fumble: '1-7',
    Weight: '3.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Broadsword',
    Category: '1-H Edged',
    Notes: '',
    Fumble: '1-3',
    Weight: '4.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Club',
    Category: '1-H Concussion',
    Notes: '',
    Fumble: '1-4',
    Weight: '5.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Composite Bow',
    Category: 'Missile',
    Notes: '',
    Fumble: '1-4',
    Weight: '3.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Light Crossbow',
    Category: 'Missile',
    Notes: '',
    Fumble: '1-5',
    Weight: '7.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Dagger',
    Category: '1-H Edged',
    Notes: '',
    Fumble: '1',
    Weight: '1.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Double-Axe',
    Category: '1-Hand/2-Hand',
    Notes: '',
    Fumble: '1-5/1-6',
    Weight: '9.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Flail',
    Category: '2-Handed',
    Notes: '',
    Fumble: '1-8',
    Weight: '6.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Halberd',
    Category: 'Pole-Arms',
    Notes: '',
    Fumble: '1-7',
    Weight: '7.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Handaxe',
    Category: '1-H Edged',
    Notes: '',
    Fumble: '1-4',
    Weight: '5.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Javelin',
    Category: 'Pole-Arms',
    Notes: '',
    Fumble: '1-4',
    Weight: '4.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Long Bow',
    Category: 'Missile',
    Notes: '',
    Fumble: '1-5',
    Weight: '3.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Mace',
    Category: '1-H Concussion',
    Notes: '',
    Fumble: '1-2',
    Weight: '5.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Morning Star',
    Category: '1-H Concussion',
    Notes: '',
    Fumble: '1-8',
    Weight: '5.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Net',
    Category: '1-H Concussion',
    Notes: '',
    Fumble: '1-6',
    Weight: '3.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Quarterstaff',
    Category: '2-Handed',
    Notes: '',
    Fumble: '1-3',
    Weight: '4.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Scimitar',
    Category: '1-H Edged',
    Notes: '',
    Fumble: '1-4',
    Weight: '4.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Short Bow',
    Category: 'Missile',
    Notes: '',
    Fumble: '1-4',
    Weight: '2.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Short Sword',
    Category: '1-H Edged',
    Notes: '',
    Fumble: '1-2',
    Weight: '3.0 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
  {
    Weapons: 'Sling',
    Category: 'Missile',
    Notes: '',
    Fumble: '1-6',
    Weight: '0.5 lbs',
    Gold: '0 gp',
    Silver: '0 sp',
    Bronze: '0 bp',
    Copper: '0 cp',
    Tin: '0 tp',
  },
]
