import { Ability } from './abilities'
import { SkillGroupType, SkillType } from './skills'

export enum Profession {
  warrior = 'warrior',
  mage = 'mage',
  animist = 'animist',
  scout = 'scout',
  ranger = 'ranger',
  bard = 'bard',
  barbarian = 'barbarian',
  burglar = 'burglar',
  conjurer = 'conjurer',
  civilian = 'civilian',
  explorer = 'explorer',
  monk = 'monk',
  rogue = 'rogue',
  scholar = 'scholar',
  shapeChanger = 'shapeChanger',
  warriorMonk = 'warriorMonk',
  wizard = 'wizard',
}

export enum DevelopmentPointTypes {
  movementAndManeuver = 'movementAndManeuver',
  weaponSkills = 'weaponSkills',
  generalSkills = 'generalSkills',
  subterfugeSkills = 'subterfugeSkills',
  magicalSkills = 'magicalSkills',
  bodyDevelopment = 'bodyDevelopment',
  languages = 'languages',
  spellLists = 'spellLists',
  martialArts = 'martialArts',
  adrenalDefense = 'adrenalDefense',
  secondarySkills = 'secondarySkills',
}

export interface ProfessionDetails {
  primaryStats: Ability[]
  professionBonuses: {
    [key in SkillType | SkillGroupType]?: number
  }
  developmentPoints: {
    [key in DevelopmentPointTypes]: number
  }
}

export const professionSelect: { [key in Profession]: string } = {
  warrior: 'professions.warrior',
  mage: 'professions.mage',
  animist: 'professions.animist',
  scout: 'professions.scout',
  ranger: 'professions.ranger',
  bard: 'professions.bard',
  barbarian: 'professions.barbarian',
  burglar: 'professions.burglar',
  conjurer: 'professions.conjurer',
  civilian: 'professions.civilian',
  explorer: 'professions.explorer',
  monk: 'professions.monk',
  rogue: 'professions.rogue',
  scholar: 'professions.scholar',
  shapeChanger: 'professions.shapeChanger',
  warriorMonk: 'professions.warriorMonk',
  wizard: 'professions.wizard',
}

export const professions: { [key in Profession]: ProfessionDetails } = {
  warrior: {
    primaryStats: [Ability.strength],
    professionBonuses: {
      generalSkills: 1,
      bodyDevelopment: 2,
      weaponSkills: 3,
    },
    developmentPoints: {
      movementAndManeuver: 3,
      weaponSkills: 5,
      generalSkills: 2,
      subterfugeSkills: 2,
      magicalSkills: 0,
      bodyDevelopment: 3,
      languages: 0,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  mage: {
    primaryStats: [Ability.intelligence],
    professionBonuses: {
      readRune: 2,
      useItem: 2,
      baseSpellOB: 2,
      directedSpells: 3,
    },
    developmentPoints: {
      movementAndManeuver: 0,
      weaponSkills: 0,
      generalSkills: 2,
      subterfugeSkills: 0,
      magicalSkills: 5,
      bodyDevelopment: 1,
      languages: 2,
      spellLists: 5,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  animist: {
    primaryStats: [Ability.intuition],
    professionBonuses: {
      generalSkills: 1,
      readRune: 1,
      useItem: 1,
      perception: 1,
      baseSpellOB: 2,
      directedSpells: 2,
    },
    developmentPoints: {
      movementAndManeuver: 1,
      weaponSkills: 1,
      generalSkills: 2,
      subterfugeSkills: 1,
      magicalSkills: 2,
      bodyDevelopment: 1,
      languages: 2,
      spellLists: 5,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  scout: {
    primaryStats: [Ability.agility],
    professionBonuses: {
      weaponSkills: 1,
      generalSkills: 1,
      subterfugeSkills: 2,
      perception: 3,
    },
    developmentPoints: {
      movementAndManeuver: 1,
      weaponSkills: 3,
      generalSkills: 3,
      subterfugeSkills: 5,
      magicalSkills: 0,
      bodyDevelopment: 2,
      languages: 1,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  ranger: {
    primaryStats: [Ability.constitution],
    professionBonuses: {
      weaponSkills: 2,
      stalkHide: 2,
      perception: 2,
      generalSkills: 3,
    },
    developmentPoints: {
      movementAndManeuver: 2,
      weaponSkills: 3,
      generalSkills: 4,
      subterfugeSkills: 2,
      magicalSkills: 0,
      bodyDevelopment: 2,
      languages: 1,
      spellLists: 1,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  bard: {
    primaryStats: [Ability.presence],
    professionBonuses: {
      weaponSkills: 1,
      generalSkills: 1,
      subterfugeSkills: 1,
      magicalSkills: 1,
      baseSpellOB: 1,
      perception: 1,
    },
    developmentPoints: {
      movementAndManeuver: 0,
      weaponSkills: 2,
      generalSkills: 2,
      subterfugeSkills: 2,
      magicalSkills: 3,
      bodyDevelopment: 1,
      languages: 3,
      spellLists: 2,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  barbarian: {
    primaryStats: [Ability.strength],
    professionBonuses: {
      weaponSkills: 2,
      generalSkills: 3,
      bodyDevelopment: 2,
    },
    developmentPoints: {
      movementAndManeuver: 1,
      weaponSkills: 5,
      generalSkills: 5,
      subterfugeSkills: 1,
      magicalSkills: 0,
      bodyDevelopment: 3,
      languages: 0,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  burglar: {
    primaryStats: [Ability.agility],
    professionBonuses: {
      generalSkills: 1,
      subterfugeSkills: 3,
      perception: 3,
    },
    developmentPoints: {
      movementAndManeuver: 2,
      weaponSkills: 1,
      generalSkills: 2,
      subterfugeSkills: 8,
      magicalSkills: 0,
      bodyDevelopment: 1,
      languages: 1,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  conjurer: {
    primaryStats: [Ability.intelligence, Ability.intuition],
    professionBonuses: {
      subterfugeSkills: 1,
      magicalSkills: 1,
      baseSpellOB: 1,
      perception: 1,
    },
    developmentPoints: {
      movementAndManeuver: 0,
      weaponSkills: 1,
      generalSkills: 1,
      subterfugeSkills: 4,
      magicalSkills: 3,
      bodyDevelopment: 1,
      languages: 1,
      spellLists: 4,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  civilian: {
    primaryStats: [
      Ability.strength,
      Ability.agility,
      Ability.constitution,
      Ability.intelligence,
      Ability.intuition,
      Ability.presence,
    ],
    professionBonuses: {
      secondarySkills: 4,
    },
    developmentPoints: {
      movementAndManeuver: 0,
      weaponSkills: 1,
      generalSkills: 2,
      subterfugeSkills: 0,
      magicalSkills: 0,
      bodyDevelopment: 1,
      languages: 0,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 11,
    },
  },
  explorer: {
    primaryStats: [Ability.constitution],
    professionBonuses: {
      weaponSkills: 1,
      generalSkills: 3,
      subterfugeSkills: 2,
      perception: 2,
    },
    developmentPoints: {
      movementAndManeuver: 2,
      weaponSkills: 2,
      generalSkills: 5,
      subterfugeSkills: 4,
      magicalSkills: 0,
      bodyDevelopment: 1,
      languages: 1,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  monk: {
    primaryStats: [Ability.agility],
    professionBonuses: {
      generalSkills: 1,
      subterfugeSkills: 1,
      magicalSkills: 1,
      martialArts: 2,
      perception: 1,
    },
    developmentPoints: {
      movementAndManeuver: 0,
      weaponSkills: 1,
      generalSkills: 2,
      subterfugeSkills: 2,
      magicalSkills: 1,
      bodyDevelopment: 1,
      languages: 1,
      spellLists: 2,
      martialArts: 3,
      adrenalDefense: 2,
      secondarySkills: 0,
    },
  },
  rogue: {
    primaryStats: [Ability.strength],
    professionBonuses: {
      weaponSkills: 2,
      generalSkills: 2,
      subterfugeSkills: 2,
    },
    developmentPoints: {
      movementAndManeuver: 2,
      weaponSkills: 4,
      generalSkills: 3,
      subterfugeSkills: 3,
      magicalSkills: 1,
      bodyDevelopment: 2,
      languages: 0,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
  scholar: {
    primaryStats: [Ability.intelligence],
    professionBonuses: {
      perception: 2,
      secondarySkills: 5,
    },
    developmentPoints: {
      movementAndManeuver: 1,
      weaponSkills: 1,
      generalSkills: 3,
      subterfugeSkills: 0,
      magicalSkills: 0,
      bodyDevelopment: 1,
      languages: 4,
      spellLists: 0,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 5,
    },
  },
  shapeChanger: {
    primaryStats: [Ability.presence],
    professionBonuses: {
      movementAndManeuver: 1,
      martialArts: 2,
      bodyDevelopment: 2,
      shapeChange: 5,
    },
    developmentPoints: {
      movementAndManeuver: 1,
      weaponSkills: 1,
      generalSkills: 1,
      subterfugeSkills: 1,
      magicalSkills: 0,
      bodyDevelopment: 3,
      languages: 1,
      spellLists: 0,
      martialArts: 3,
      adrenalDefense: 3,
      secondarySkills: 0,
    },
  },
  warriorMonk: {
    primaryStats: [Ability.strength],
    professionBonuses: {
      generalSkills: 1,
      martialArts: 3,
      bodyDevelopment: 2,
    },
    developmentPoints: {
      movementAndManeuver: 0,
      weaponSkills: 1,
      generalSkills: 1,
      subterfugeSkills: 2,
      magicalSkills: 0,
      bodyDevelopment: 3,
      languages: 0,
      spellLists: 0,
      martialArts: 5,
      adrenalDefense: 3,
      secondarySkills: 0,
    },
  },
  wizard: {
    primaryStats: [Ability.intelligence, Ability.intuition],
    professionBonuses: {
      magicalSkills: 2,
      baseSpellOB: 2,
    },
    developmentPoints: {
      movementAndManeuver: 0,
      weaponSkills: 0,
      generalSkills: 2,
      subterfugeSkills: 0,
      magicalSkills: 5,
      bodyDevelopment: 1,
      languages: 2,
      spellLists: 5,
      martialArts: 0,
      adrenalDefense: 0,
      secondarySkills: 0,
    },
  },
}
